name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-snapshot:
    if: github.repository_owner == 'TAKETODAY'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4.1.2
      - name: Set up JDK 17 and Maven Central Repository
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: adopt
          server-id: snapshots
          server-username: SNAPSHOTS_USERNAME
          server-password: SNAPSHOTS_TOKEN
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.1.0

      - name: Deploy snapshots
        run: ./gradlew --no-daemon publish --max-workers=4 -PrepoUsername=$SNAPSHOTS_USERNAME -PrepoPassword=$SNAPSHOTS_TOKEN -Psigning.keyId=$SIGNID -Psigning.password=$SIGNPWD
        env:
          SNAPSHOTS_TOKEN: ${{ secrets.SNAPSHOTS_TOKEN }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          SIGNID: ${{secrets.SIGNID}}
          SIGNPWD: ${{secrets.SIGNPWD}}
